### ISSUE TITLE
Error when loading silent_renew.html

### ISSUE THREAD

**Issue by hai-nguyen1112** [maxmantz/redux-oidc-example#25]
Hi, thank you again so much for this library. I appreciate your work.

I have an error when loading the silent_renew.html file.

This is my userManager settings:
<img width="797" alt="Screen Shot 2019-07-15 at 2 13 36 PM" src="https://user-images.githubusercontent.com/45631748/61239234-7243c180-a70c-11e9-8fa3-89eb2fcea7a9.png">

This is the content of the silent_renew.html file:
<img width="527" alt="Screen Shot 2019-07-15 at 2 27 12 PM" src="https://user-images.githubusercontent.com/45631748/61239384-c0f15b80-a70c-11e9-91b1-871231b363e8.png">

I also added the silent_redirect_uri to the identity provider:
<img width="629" alt="Screen Shot 2019-07-15 at 2 14 13 PM" src="https://user-images.githubusercontent.com/45631748/61239428-dc5c6680-a70c-11e9-9f78-551d803d3d34.png">

However, when the page silent_renew.html was being loaded, there was an error in the console as follows:
<img width="652" alt="Screen Shot 2019-07-15 at 2 15 23 PM" src="https://user-images.githubusercontent.com/45631748/61239486-fdbd5280-a70c-11e9-8e87-39b52db29d9c.png">

Could you please let me know what I did wrong and how to solve this error? Thank you.

**Comment by maxmantz** [comment]
Hi and thanks again for your kind words.

The setup you have looks fine, except for the HTML file. You cannot simply put an ES6 import statement in a `<script />` tag and expect it to work. Explaining why this is is beyond the scope of this libary and this issue. I strongly recommend familiarizing yourself with tools like Webpack in order to resolve this issue.
